export const BENCHMARK_PROCESS = "Zv4NMG3qYgCtLLd9UTp8c0lhUjAnok2bVJahSwe1CkM";
export const EMBEDDING_PROCESS = "0I4lfmafx816miHSJ78KFoQE9vc0pu79Czgp0VNWO84";
// export const BENCHMARK_PROCESS = "xLlcWNqzvVJHOYpgFP9QV-FSF4mcmPtk8xjverzRK3U";
// export const EMBEDDING_PROCESS = "jjEkZTRO_tL4BrhMm34TLXM_wg3zoXINK6fIbp3OSUo";